cc_library(
    name = "status",
    hdrs = ["status.h"],
    copts = ["-std=c++1z"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "context",
    hdrs = ["context.h"],
    copts = ["-std=c++1z"],
    visibility = ["//visibility:public"],
    deps = [":status"]
)
